
language: go

go:
  - 1.13.x

env:
  - GO111MODULE=on

before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint
  - go get github.com/mattn/goveralls

script:
  - golangci-lint run
  - go test -count=1 -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - goveralls -service=travis-ci -coverprofile=coverage.txt
